### ISSUE TITLE
incorrect checksum for freed object - object was probably modified after being freed

### ISSUE THREAD

**Issue by xxxzhi** [EugeneNdiaye/GAPSAFE_SGL#1]
Hello. It crash when I test the sgl_path method like this:

```
import numpy as np
from sgl_tools import generate_data
from sgl import sgl_path
import time
import matplotlib.pyplot as plt
from matplotlib import rc
import pandas as pd

n_samples = 100
# size_group = 50  # all groups have size = size_group

size_groups = 285 * np.ones(4, order='F',
                                   dtype=np.intc)
size_groups = np.asarray([244, 312, 230, 352])  // comment this line will success.
n_features = size_groups.sum()
print(size_groups)
X, y = generate_data(n_samples, n_features, size_groups, rho=0.4)
omega = np.sqrt(size_groups)
sgl_path(X, y, size_groups, omega, screen=5, lambdas=[22,30], tau=0.5, eps=1e-6);exit();

```

here is the crash log:

[244 312 230 352]
Warning did not converge ... t = 0 gap = 142727.599036                    eps = 1e-06 n_iter = 29999.0
Warning did not converge ... t = 1 gap = 189961.959137                    eps = 1e-06 n_iter = 29999.0
Python(21947,0x7fff73a27000) malloc: *** error for object 0x7fc98a323a08: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
[1]    21947 abort      /usr/local/bin/python example.py

Could you help me to fix the problem ? Thanks in advance.

 When I use `$size_groups = 285 * np.ones(4, order='F', dtype=np.intc)$`, it is no error.

**Comment by xuhs-haha** [comment]
hi,
You may have sent this email to a wrong guy. Maybe you should check the email address :-)
Best regards

**Comment by xxxzhi** [comment]
@xuhs-haha , oh, thanks. Here is the reason.

```
// sgl.py line 124
g_start = np.cumsum(size_groups, dtype=np.intc) - size_groups[0]
```

fix by:

```
g_start = np.asarray([0] + np.cumsum(size_groups, dtype=np.intc)[:-1].tolist(), dtype=np.int32)
```

Thanks.

**Comment by EugeneNdiaye** [comment]
Dear all, thanks for the comment.
Please use the latest version in https://github.com/EugeneNdiaye/Gap_Safe_Rules

I will try to check if the bugs remain and add more comments on the code. Please do not hesitate to give feedbacks.

Eugene
